export const ROOT_PATH = '/'
export const LOGIN_PATH = '/login'
export const APP_PATH = '/app'
export const APP_HOME_PATH = '/app/dashboard'

export const NAV_GROUPS = ['Tong quan', 'Quan ly']

const ALL_STAFF = ['admin', 'manager', 'trainer', 'receptionist']
const OPS_STAFF = ['admin', 'manager', 'receptionist']
const TRAINING_STAFF = ['admin', 'manager', 'trainer']
const MANAGER_STAFF = ['admin', 'manager']

export const APP_ROUTES = [
  {
    key: 'dashboard',
    navKey: 'dashboard',
    path: APP_HOME_PATH,
    label: 'Dashboard',
    title: 'Dashboard',
    group: 'Tong quan',
    roles: ALL_STAFF,
    status: 'ready',
    description: 'Operational overview with live dashboard metrics for admin and manager roles.',
    plannedApis: [
      'GET /api/v1/auth/me',
      'GET /api/v1/dashboard/summary',
      'GET /api/v1/dashboard/revenue',
      'GET /api/v1/dashboard/plans',
      'GET /api/v1/dashboard/members/recent',
      'GET /api/v1/dashboard/sessions/today',
    ],
  },
  {
    key: 'members',
    navKey: 'members',
    path: '/app/members',
    label: 'Members',
    title: 'Members',
    group: 'Tong quan',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Member create, direct lookup, profile, activation, and subscriptions panel.',
    plannedApis: [
      'POST /api/v1/members',
      'GET /api/v1/members/:id',
      'PATCH /api/v1/members/:id/activate',
      'GET /api/v1/members/:id/subscriptions',
    ],
    plannedScope: ['Create member profile', 'Open member profile by ID', 'Activate offline payment', 'View member subscriptions'],
  },
  {
    key: 'member-new',
    navKey: 'members',
    path: '/app/members/new',
    label: 'New member',
    title: 'New member',
    group: 'Tong quan',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Create a member profile before subscription setup.',
    plannedApis: ['POST /api/v1/members'],
    plannedScope: ['Create member profile'],
    nav: false,
  },
  {
    key: 'member-detail',
    navKey: 'members',
    path: '/app/members/:id',
    label: 'Member detail',
    title: 'Member detail',
    group: 'Tong quan',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Live member profile, subscription history, and offline activation.',
    plannedApis: [
      'GET /api/v1/members/:id',
      'PATCH /api/v1/members/:id/activate',
      'GET /api/v1/members/:id/subscriptions',
    ],
    plannedScope: ['Profile summary', 'Subscription history', 'Offline payment activation'],
    nav: false,
  },
  {
    key: 'attendance',
    navKey: 'attendance',
    path: '/app/attendance',
    label: 'Attendance',
    title: 'Attendance',
    group: 'Tong quan',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Check-in, missed-session report, makeup attendance, and subscription history entry point.',
    plannedApis: [
      'POST /api/v1/attendance/checkin',
      'POST /api/v1/attendance/report',
      'POST /api/v1/attendance/makeup',
      'GET /api/v1/subscriptions/:id/attendance',
    ],
    plannedScope: ['Free check-in', 'Report missed attendance', 'Create makeup attendance', 'Open subscription attendance history'],
  },
  {
    key: 'sessions',
    navKey: 'sessions',
    path: '/app/sessions',
    label: 'Sessions',
    title: 'Sessions',
    group: 'Tong quan',
    roles: TRAINING_STAFF,
    status: 'ready',
    description: 'Session list, creation shell, enrollment, and session check-in foundation.',
    plannedApis: [
      'POST /api/v1/sessions',
      'GET /api/v1/sessions',
      'GET /api/v1/sessions/:id',
      'POST /api/v1/sessions/:id/enroll',
      'POST /api/v1/sessions/:id/checkin',
    ],
    plannedScope: ['Filter sessions', 'Create session', 'Enroll subscription', 'Check in enrolled member'],
  },
  {
    key: 'session-new',
    navKey: 'sessions',
    path: '/app/sessions/new',
    label: 'New session',
    title: 'New session',
    group: 'Tong quan',
    roles: TRAINING_STAFF,
    status: 'ready',
    description: 'Create a scheduled class session.',
    plannedApis: ['POST /api/v1/sessions', 'GET /api/v1/branches', 'GET /api/v1/courses'],
    plannedScope: ['Create session'],
    nav: false,
  },
  {
    key: 'session-detail',
    navKey: 'sessions',
    path: '/app/sessions/:id',
    label: 'Session detail',
    title: 'Session detail',
    group: 'Tong quan',
    roles: TRAINING_STAFF,
    status: 'ready',
    description: 'Detail shell for one class session.',
    plannedApis: ['GET /api/v1/sessions/:id', 'POST /api/v1/sessions/:id/enroll', 'POST /api/v1/sessions/:id/checkin'],
    plannedScope: ['Session details', 'Enrollment list', 'Session check-in'],
    nav: false,
  },
  {
    key: 'reports',
    navKey: 'reports',
    path: '/app/reports',
    label: 'Reports',
    title: 'Reports',
    group: 'Tong quan',
    roles: MANAGER_STAFF,
    status: 'blocked',
    description: 'Report and dashboard aggregates need a later backend dashboard/report API cycle.',
    plannedApis: ['Future dashboard/report endpoints'],
    plannedScope: ['Live dashboard metrics', 'Revenue reporting', 'Operational reports'],
  },
  {
    key: 'subscriptions',
    navKey: 'subscriptions',
    path: '/app/subscriptions',
    label: 'Subscriptions',
    title: 'Subscriptions',
    group: 'Quan ly',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Create pending subscriptions and manage lifecycle actions.',
    plannedApis: [
      'POST /api/v1/subscriptions',
      'GET /api/v1/subscriptions/:id',
      'PATCH /api/v1/subscriptions/:id/suspend',
      'PATCH /api/v1/subscriptions/:id/unsuspend',
      'PATCH /api/v1/subscriptions/:id/expire',
      'POST /api/v1/subscriptions/:id/refund',
    ],
    plannedScope: ['Create pending subscription', 'Open subscription by ID', 'Suspend or unsuspend', 'Expire or refund'],
  },
  {
    key: 'subscription-new',
    navKey: 'subscriptions',
    path: '/app/subscriptions/new',
    label: 'New subscription',
    title: 'New subscription',
    group: 'Quan ly',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Create a pending subscription from member, course, and branch references.',
    plannedApis: ['POST /api/v1/subscriptions', 'GET /api/v1/courses', 'GET /api/v1/branches'],
    plannedScope: ['Create pending subscription'],
    nav: false,
  },
  {
    key: 'subscription-attendance',
    navKey: 'attendance',
    path: '/app/subscriptions/:id/attendance',
    label: 'Subscription attendance',
    title: 'Subscription attendance',
    group: 'Tong quan',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Subscription-scoped attendance history and quick attendance actions.',
    plannedApis: [
      'GET /api/v1/subscriptions/:id/attendance',
      'POST /api/v1/attendance/checkin',
      'POST /api/v1/attendance/report',
      'POST /api/v1/attendance/makeup',
    ],
    plannedScope: ['History', 'Check-in', 'Report missed', 'Makeup attendance'],
    nav: false,
  },
  {
    key: 'subscription-detail',
    navKey: 'subscriptions',
    path: '/app/subscriptions/:id',
    label: 'Subscription detail',
    title: 'Subscription detail',
    group: 'Quan ly',
    roles: OPS_STAFF,
    status: 'ready',
    description: 'Detail shell for one subscription lifecycle view.',
    plannedApis: ['GET /api/v1/subscriptions/:id', 'GET /api/v1/subscriptions/:id/attendance'],
    plannedScope: ['Subscription detail', 'Lifecycle actions', 'Attendance shortcut'],
    nav: false,
  },
  {
    key: 'employees',
    navKey: 'employees',
    path: '/app/employees',
    label: 'Employees',
    title: 'Employees',
    group: 'Quan ly',
    roles: ['admin'],
    status: 'ready',
    description: 'Admin-only staff account management, profile updates, and password reset.',
    plannedApis: [
      'POST /api/v1/employees',
      'GET /api/v1/employees',
      'GET /api/v1/employees/:id',
      'PATCH /api/v1/employees/:id',
      'PATCH /api/v1/employees/:id/password',
    ],
    plannedScope: ['List staff', 'Create staff account', 'Update staff profile', 'Reset password'],
  },
  {
    key: 'employee-new',
    navKey: 'employees',
    path: '/app/employees/new',
    label: 'New employee',
    title: 'New employee',
    group: 'Quan ly',
    roles: ['admin'],
    status: 'ready',
    description: 'Create an admin-managed staff account.',
    plannedApis: ['POST /api/v1/employees', 'GET /api/v1/branches'],
    plannedScope: ['Create staff account'],
    nav: false,
  },
  {
    key: 'employee-detail',
    navKey: 'employees',
    path: '/app/employees/:id',
    label: 'Employee detail',
    title: 'Employee detail',
    group: 'Quan ly',
    roles: ['admin'],
    status: 'ready',
    description: 'Update staff profile, deactivate, and reset password.',
    plannedApis: ['GET /api/v1/employees/:id', 'PATCH /api/v1/employees/:id', 'PATCH /api/v1/employees/:id/password'],
    plannedScope: ['Profile update', 'Status update', 'Password reset'],
    nav: false,
  },
  {
    key: 'courses',
    navKey: 'courses',
    path: '/app/settings/courses',
    label: 'Courses',
    title: 'Courses',
    group: 'Quan ly',
    roles: MANAGER_STAFF,
    status: 'ready',
    description: 'Course/package CRUD and selectable course data for subscription forms.',
    plannedApis: ['POST /api/v1/courses', 'GET /api/v1/courses', 'GET /api/v1/courses/:id', 'PATCH /api/v1/courses/:id', 'DELETE /api/v1/courses/:id'],
    plannedScope: ['List courses', 'Create course', 'Edit course', 'Delete course'],
  },
  {
    key: 'course-detail',
    navKey: 'courses',
    path: '/app/settings/courses/:id',
    label: 'Course detail',
    title: 'Course detail',
    group: 'Quan ly',
    roles: MANAGER_STAFF,
    status: 'ready',
    description: 'Course detail, edit, and delete.',
    plannedApis: ['GET /api/v1/courses/:id', 'PATCH /api/v1/courses/:id', 'DELETE /api/v1/courses/:id'],
    plannedScope: ['Course details', 'Edit course', 'Delete course'],
    nav: false,
  },
  {
    key: 'branches',
    navKey: 'branches',
    path: '/app/settings/branches',
    label: 'Branches',
    title: 'Branches',
    group: 'Quan ly',
    roles: MANAGER_STAFF,
    status: 'ready',
    description: 'Branch CRUD and nearby search support for later forms.',
    plannedApis: ['POST /api/v1/branches', 'GET /api/v1/branches', 'GET /api/v1/branches/:id', 'PATCH /api/v1/branches/:id', 'DELETE /api/v1/branches/:id', 'GET /api/v1/branches/nearby'],
    plannedScope: ['List branches', 'Create branch', 'Edit branch', 'Nearby search'],
  },
  {
    key: 'branch-detail',
    navKey: 'branches',
    path: '/app/settings/branches/:id',
    label: 'Branch detail',
    title: 'Branch detail',
    group: 'Quan ly',
    roles: MANAGER_STAFF,
    status: 'ready',
    description: 'Branch detail, edit, and delete.',
    plannedApis: ['GET /api/v1/branches/:id', 'PATCH /api/v1/branches/:id', 'DELETE /api/v1/branches/:id'],
    plannedScope: ['Branch details', 'Edit branch', 'Delete branch'],
    nav: false,
  },
  {
    key: 'payments',
    navKey: 'payments',
    path: '/app/payments',
    label: 'Payments',
    title: 'Payments',
    group: 'Quan ly',
    roles: OPS_STAFF,
    status: 'blocked',
    description: 'Payment workspace is tracked as a future UI surface after subscription/member flows.',
    plannedApis: ['Subscription activation and refund endpoints'],
    plannedScope: ['Offline payment confirmation', 'Refund review', 'Payment history'],
  },
]

export const APP_NAV_ITEMS = APP_ROUTES.filter((route) => route.nav !== false)

export const NOT_FOUND_ROUTE = {
  key: 'not-found',
  navKey: null,
  path: '*',
  label: 'Not found',
  title: 'Page not found',
  roles: [],
  status: 'system',
}
