# Health check
GET http://localhost:8080/ping

###

# Member registration
POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
  "ccid": "012345678901",
  "full_name": "Nguyen Van A",
  "email": "a@example.com",
  "phone": "0900000000",
  "gender": "male",
  "level": "basic"
}

###

# Member registration 2
POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
  "ccid": "012345678902",
  "full_name": "Tran Thi B",
  "email": "b@example.com",
  "phone": "0900000001",
  "gender": "female",
  "level": "advanced"
}