export const dashboardData = {
  updatedAtLabel: 'Sample snapshot',
  kpis: [
    {
      key: 'members',
      label: 'Active members',
      value: '3,847',
      delta: '+128 this month',
      tone: 'up',
      accent: true,
    },
    {
      key: 'revenue',
      label: 'Monthly revenue',
      value: '142M VND',
      delta: '+12.4% vs last month',
      tone: 'up',
      accent: false,
    },
    {
      key: 'checkins',
      label: 'Today check-ins',
      value: '284',
      delta: '-8 vs yesterday',
      tone: 'down',
      accent: false,
    },
    {
      key: 'classes',
      label: 'Classes this week',
      value: '48',
      delta: '6 classes per day avg',
      tone: 'neutral',
      accent: false,
    },
  ],
  revenue: [
    { day: 'Mon', value: 14.2, tone: 'mid' },
    { day: 'Tue', value: 18.1, tone: 'mid' },
    { day: 'Wed', value: 12.4, tone: 'mid' },
    { day: 'Thu', value: 22.0, tone: 'mid' },
    { day: 'Fri', value: 16.0, tone: 'mid' },
    { day: 'Sat', value: 24.5, tone: 'accent' },
    { day: 'Sun', value: 20.1, tone: 'base' },
  ],
  planDistribution: [
    { label: 'Elite', value: 1280, color: 'var(--color-accent)' },
    { label: 'Pro', value: 2050, color: 'rgba(255, 70, 20, 0.52)' },
    { label: 'Basic', value: 517, color: 'var(--color-surface-strong)' },
  ],
  latestMembers: [
    {
      name: 'Nguyen Minh Khoa',
      phone: '0912 345 678',
      plan: 'Elite',
      trainer: 'Minh Tuan',
      status: 'Paid',
      statusTone: 'success',
      planTone: 'danger',
    },
    {
      name: 'Tran Thu Huong',
      phone: '0987 654 321',
      plan: 'Pro',
      trainer: 'Lan Anh',
      status: 'Paid',
      statusTone: 'success',
      planTone: 'warning',
    },
    {
      name: 'Pham Duc Long',
      phone: '0901 111 222',
      plan: 'Basic',
      trainer: 'Unassigned',
      status: 'Pending',
      statusTone: 'warning',
      planTone: 'neutral',
    },
    {
      name: 'Le Bao Chau',
      phone: '0933 222 111',
      plan: 'Pro',
      trainer: 'Thu Ha',
      status: 'Paid',
      statusTone: 'success',
      planTone: 'warning',
    },
    {
      name: 'Vo Quang Vinh',
      phone: '0966 333 555',
      plan: 'Elite',
      trainer: 'Quang Hai',
      status: 'Awaiting payment',
      statusTone: 'danger',
      planTone: 'danger',
    },
  ],
  todaySessions: [
    {
      time: '06:00',
      name: 'Morning HIIT',
      trainer: 'Lan Anh',
      room: 'Room 1',
      capacity: 18,
      maxCapacity: 20,
      tone: 'ok',
    },
    {
      time: '07:30',
      name: 'Boxing Fundamentals',
      trainer: 'Quang Hai',
      room: 'Combat Floor',
      capacity: 15,
      maxCapacity: 15,
      tone: 'full',
    },
    {
      time: '09:00',
      name: 'Yoga Morning Flow',
      trainer: 'Thu Ha',
      room: 'Yoga Room',
      capacity: 10,
      maxCapacity: 15,
      tone: 'ok',
    },
    {
      time: '12:00',
      name: 'Powerlifting Club',
      trainer: 'Minh Tuan',
      room: 'Strength Zone',
      capacity: 12,
      maxCapacity: 12,
      tone: 'warn',
    },
    {
      time: '18:00',
      name: 'Evening HIIT',
      trainer: 'Lan Anh',
      room: 'Room 1',
      capacity: 14,
      maxCapacity: 20,
      tone: 'ok',
    },
    {
      time: '19:30',
      name: 'Muay Thai Intermediate',
      trainer: 'Quang Hai',
      room: 'Combat Floor',
      capacity: 15,
      maxCapacity: 15,
      tone: 'full',
    },
  ],
}
